name: GitHub Actions Demo
on: [push]
jobs:
 cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
            node:version: '14'
      - name: Install dependencies
        run: npm install && npm install wait-on
        run: npm start & wait-on http://localhost:3000  
      - name: Cypress run
        uses: cypress-io/github-action@v2
      - run: npx cypress run --record --key ${{ secrets.CYPRESS_TOKEN }}